#version 450
#extension GL_KHR_shader_subgroup_arithmetic : require

layout(binding = 0) readonly buffer i_ { float ip[]; };
layout(binding = 1)          buffer t_ { float mx[]; };

layout(local_size_z = 32) in;

const uint n_ctx = 1024;

void main() {
  uint h = gl_GlobalInvocationID.x;
  uint i = gl_GlobalInvocationID.y;
  uint j = gl_GlobalInvocationID.z;
  uint s = gl_WorkGroupID.z;
  uint j_size = gl_NumWorkGroups.z;
  uint p = h * n_ctx * j_size + i * j_size + j;
  uint m = h * n_ctx * 32 + i * 32 + s;

  float mm = subgroupMax(ip[p]);
  if (subgroupElect()) { mx[m] = mm; }
}
