#version 450
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_EXT_shader_atomic_float2 : require

layout(binding = 0) readonly buffer i_ { float ip[]; };
layout(binding = 1)          buffer t_ { float mx[]; };

layout(local_size_y = 32) in;

const uint n_ctx = 1024;

void main() {
  uint h = gl_GlobalInvocationID.x;
  uint i = gl_GlobalInvocationID.y;
  uint j = gl_GlobalInvocationID.z;
  uint p = h * n_ctx * n_ctx + i * n_ctx + j;
  uint m = h * n_ctx + i;

  if (gl_GlobalInvocationID.x == 0) { mx[m] = 0; }
  barrier();

  atomicMax(mx[m], subgroupMax(ip[p]));
}
